### ISSUE TITLE
Translate all the documentation into Spanish

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [denolib/awesome-deno#115]
Hello, I would like to be able to translate all the documentation into Spanish, could you take that task?

**Comment by FranciscoImanolSuarez** [comment]
I would like to pass to my language the modules that comprise the following link

https://github.com/denoland/deno/tree/master/docs

**Comment by kt3k** [comment]
This repository for awesome-deno list, not for the manual documentation.

BTW spanish version of official deno website is available at https://deno-es.vercel.app/ (repository: https://github.com/jheysonsaav/deno_website2 )
