### ISSUE TITLE
Microsoft SQL Server modules like tedious or mssql 

### ISSUE THREAD

**Issue by naimsulejmani** [denolib/awesome-deno#158]
I saw only for Postgres SQL, MySQL, but not for SQL Server, I searched but didn't find any

**Comment by Micahnator** [comment]
I too am hoping to see an mssql module.

**Comment by kt3k** [comment]
Now Deno officially tracks the wanted modules in https://github.com/denoland/wanted_modules

There's an issue for mssql and tedius there. Please follow that issue instead of this one. https://github.com/denoland/wanted_modules/issues/19
