### ISSUE TITLE
Detach the repository

### ISSUE THREAD

**Issue by kidonng** [denolib/awesome-deno#190]
Forked repo doesn't show in GitHub search by default, which makes it hard to discover.

Since [awesome-deno-cn](https://github.com/olivewind/awesome-deno-cn) is no longer updating (archived), it's better to contact GitHub to detach this repository.

https://help.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork

**Comment by TheWizardBear** [comment]
Has there been any progress on this? It seems like this would be a good idea, especially as searching "awesome-deno" doesn't seem to show this repository because it is a fork.

**Comment by kidonng** [comment]
@TheWizardBear Just ask one of the maintainers to contact GitHub support I think? It shouldn't take more than five minutes to write a request.

**Comment by zekth** [comment]
I think thats @kevinkassimo who has the admin permissions on the repo

**Comment by kidonng** [comment]
I think everyone can contact GitHub support about this issue, but an organization member's request have the advantage to get more chance to be approved.

**Comment by TheWizardBear** [comment]
@kidonng So I've sent Github support a message, but they said they can't do anything until they have confirmation from an admin.

**Comment by kt3k** [comment]
Now it's detached from https://github.com/olivewind/awesome-deno-cn. Thank you for your suggestion! @kidonng
