### ISSUE TITLE
replace the modules listing with dynamic listings

### ISSUE THREAD

**Issue by balupton** [denolib/awesome-deno#215]
- https://deno.land/x
- https://nest.land
- https://www.npmjs.com/search?q=keywords:deno-entry - packages that provide a deno entry point `package.json:deno`, such as those created and consumed by [make-deno-edition](https://github.com/bevry/make-deno-edition)

**Comment by kidonng** [comment]
This list is curated, examined, and categorized by hand, which is difficult to achieve via dynamic lists. And I personally believe sorting by stars/downloads is not really a good way to promote really good resources.

**Comment by zekth** [comment]
> This list is curated, examined, and categorized by hand

> sorting by stars/downloads is not really a good way to promote really good resources

That's the point.

**Comment by balupton** [comment]
How bout a section for dynamic lists as well? That way consumers can find packages that may not yet have had PRs submitted here.

My concern is the gatekeeping of curation and the tedium of PR submissions, would deter PRs for many good packages, keeping them from public awareness.

**Comment by zekth** [comment]
This proposal could fit. What do you think @kevinkassimo @kt3k ?

**Comment by kt3k** [comment]
I agree with a sectoin for dynamic lists. That must be a good resource for deno users 👍 

I disagree with the original suggestion `replace the modules listing with dynamic listings`. I think the list should be curated by the maintainers because that is the point of `awesome` list.
