### ISSUE TITLE
Some modules for Deno, write by myself.

### ISSUE THREAD

**Issue by BoltDoggy** [denolib/awesome-deno#27]
https://deno.boltdoggy.com/

- dpm - deno package manager, install global command for deno.
- dcc - deno cache clean, reloading deps when next running.

## dpm

deno package manager, install global command for deno.

``` sh
# install
deno https://deno.boltdoggy.com/x/dpm/install.js

# using
dpm <remote_url> <command_name> # install command of this remote_url to global
# more examples, you can see `dcc install`.
```

## dcc

deno cache clean, reloading deps when next running.

```sh
# install
dpm https://deno.boltdoggy.com/x/dcc/mod.js dcc

# using
dcc <remote_url> # remove cache for this remote_url
# or
dcc --all # or dcc -a, remove all cache
```

**Comment by kevinkassimo** [comment]
Looks great! Could you submit a PR that add links to your repositories? Thanks!

**Comment by BoltDoggy** [comment]
https://github.com/denolib/awesome-deno/pull/28

**Comment by hashrock** [comment]
Thank you for submitting PR!
