### ISSUE TITLE
denoget is DEPRECATED

### ISSUE THREAD

**Issue by skimmilk6877** [denolib/awesome-deno#288]
I think it is good to remove DEPRECATED module.

**Comment by skimmilk6877** [comment]
and typescript-deno-plugin

**Comment by kt3k** [comment]
I agree we should remove deprecated modules.

That's actually required in the official 'awesome' guideline https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md

> Does not contain items that are unmaintained, has archived repo, deprecated, or missing docs.

**Comment by skimmilk6877** [comment]
there is tons of deprecated modules since deno api changing.
