### ISSUE TITLE
Suggestion: Add an integrations/platforms section?

### ISSUE THREAD

**Issue by teleclimber** [denolib/awesome-deno#345]
This would be for platforms that expose Deno as part of their functionality or that let you use Deno to deploy or run or whatever.

Examples:

- Slack https://api.slack.com/future/functions/custom
- Netlify https://docs.netlify.com/edge-functions/overview/
- Supabase https://supabase.com/docs/guides/functions
- Astro: https://docs.astro.build/en/guides/deploy/deno/

**Comment by kt3k** [comment]
Makes sense!

**Comment by teleclimber** [comment]
See https://github.com/denolib/awesome-deno/pull/346

**Comment by kt3k** [comment]
Thanks for the suggestion!
