### ISSUE TITLE
Unpublish denolib/setup-deno from GitHub Actions marketplace?

### ISSUE THREAD

**Issue by jcbhmr** [denolib/awesome-deno#375]
Right now the https://github.com/denolib/setup-deno action is still listed on the GitHub Actions marketplace. https://github.com/marketplace/actions/setup-deno-environment I think that it would be a good idea to remove its listing from the marketplace but **keep the repository**. Don't worry; delisting it doesn't affect usage. Users can still `- uses: denolib/setup-deno@vN` even though it's not published to the marketplace. In fact, you can use _any_ GitHub repo as an action; even those not published to the marketplace! The marketplace is just for advertising/searchability.

here's the docs on how to unpublish from the marketplace: https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#removing-an-action-from-github-marketplace

> Select Publish this action to the GitHub Marketplace to remove the check from the box.

why this is a good idea: it removes the influx of new users who search for "deno" on the github actions marketplace.

why did i open this issue here: because the setup-deno repo is archived  and i couldn't find a .github repo or other generic org-level issue board. 🤷‍♀️

**Comment by zhmushan** [comment]
@kt3k I have added permissions for you. I found that the "Publish this release to the GitHub Marketplace" button is disabled to me, could it be that I still lack certain permissions?

**Comment by kt3k** [comment]
@zhmushan Thanks for giving me the access! And now I see the same above issue 😅 

I messaged @keroxp (org owner) about this situation

**Comment by kt3k** [comment]
I got owner role of the org now.

Unpublished `denolib/setup-deno` from the marketplace. Thanks for your suggestion! @jcbhmr
